#!/usr/bin/env bash                                                           
# Install and configure HAproxy on your lb-01 server                          
sudo apt-get update
sudo apt-get -y install haproxy
options="\n\tbind :80\n\tmode http\n\tuse_backend mybackend\nbackend mybackend\n\tbalance roundrobin\n\tserver 20216-web-01 3.234.243.169:80 check\n\tserver 20216-web-02 3.235.239.11:80 check"
sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sed -i "s/frontend myconf/&$options/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart