#!/usr/bin/env bash
# Prints superstitious numbers from china japan and italy
declare -i a;
a=0;
while (( a <= 20 ))
  do
    case $a in
      17)
         echo "bad luck from Italy"
         ;;
      9) echo "bad luck from Japan"
         ;;
      4) echo "bad luck from China"
         ;;
      *)
         echo "$a"
      esac
    (( a+=1 ));
  done
