#!/usr/bin/env bash
# check if file exists and is not empty
# checks if file is a regular file
file="school"
if [[ -e $file ]]
 then
     echo "school file exists"
     if [[ -s $file ]]
       then
           echo "school file is not  empty"
     else
           echo "school if is  empty"
     fi
     if [[ -f $file ]]
       then
           echo "school is a regular file"
     fi
else
        echo "school if does not exist"
fi
